//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.FactorABMCServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Factor", Namespace="http://schemas.datacontract.org/2004/07/FactorService")]
    [System.SerializableAttribute()]
    public partial class Factor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMVC.FactorABMCServicio.FactorValor Valor1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMVC.FactorABMCServicio.FactorValor Valor2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMVC.FactorABMCServicio.FactorValor Valor3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMVC.FactorABMCServicio.FactorValor[] ValoresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebMVC.FactorABMCServicio.FactorValor Valor1 {
            get {
                return this.Valor1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Valor1Field, value) != true)) {
                    this.Valor1Field = value;
                    this.RaisePropertyChanged("Valor1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebMVC.FactorABMCServicio.FactorValor Valor2 {
            get {
                return this.Valor2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Valor2Field, value) != true)) {
                    this.Valor2Field = value;
                    this.RaisePropertyChanged("Valor2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebMVC.FactorABMCServicio.FactorValor Valor3 {
            get {
                return this.Valor3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Valor3Field, value) != true)) {
                    this.Valor3Field = value;
                    this.RaisePropertyChanged("Valor3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebMVC.FactorABMCServicio.FactorValor[] Valores {
            get {
                return this.ValoresField;
            }
            set {
                if ((object.ReferenceEquals(this.ValoresField, value) != true)) {
                    this.ValoresField = value;
                    this.RaisePropertyChanged("Valores");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FactorValor", Namespace="http://schemas.datacontract.org/2004/07/FactorService")]
    [System.SerializableAttribute()]
    public partial class FactorValor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FactorABMCServicio.IFactorServicio")]
    public interface IFactorServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFactorServicio/Listar", ReplyAction="http://tempuri.org/IFactorServicio/ListarResponse")]
        WebMVC.FactorABMCServicio.Factor[] Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFactorServicio/Listar", ReplyAction="http://tempuri.org/IFactorServicio/ListarResponse")]
        System.Threading.Tasks.Task<WebMVC.FactorABMCServicio.Factor[]> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFactorServicio/Guardar", ReplyAction="http://tempuri.org/IFactorServicio/GuardarResponse")]
        void Guardar(WebMVC.FactorABMCServicio.Factor f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFactorServicio/Guardar", ReplyAction="http://tempuri.org/IFactorServicio/GuardarResponse")]
        System.Threading.Tasks.Task GuardarAsync(WebMVC.FactorABMCServicio.Factor f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFactorServicio/Eliminar", ReplyAction="http://tempuri.org/IFactorServicio/EliminarResponse")]
        void Eliminar(WebMVC.FactorABMCServicio.Factor f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFactorServicio/Eliminar", ReplyAction="http://tempuri.org/IFactorServicio/EliminarResponse")]
        System.Threading.Tasks.Task EliminarAsync(WebMVC.FactorABMCServicio.Factor f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFactorServicio/GetById", ReplyAction="http://tempuri.org/IFactorServicio/GetByIdResponse")]
        WebMVC.FactorABMCServicio.Factor GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFactorServicio/GetById", ReplyAction="http://tempuri.org/IFactorServicio/GetByIdResponse")]
        System.Threading.Tasks.Task<WebMVC.FactorABMCServicio.Factor> GetByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFactorServicioChannel : WebMVC.FactorABMCServicio.IFactorServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FactorServicioClient : System.ServiceModel.ClientBase<WebMVC.FactorABMCServicio.IFactorServicio>, WebMVC.FactorABMCServicio.IFactorServicio {
        
        public FactorServicioClient() {
        }
        
        public FactorServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FactorServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FactorServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FactorServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebMVC.FactorABMCServicio.Factor[] Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<WebMVC.FactorABMCServicio.Factor[]> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public void Guardar(WebMVC.FactorABMCServicio.Factor f) {
            base.Channel.Guardar(f);
        }
        
        public System.Threading.Tasks.Task GuardarAsync(WebMVC.FactorABMCServicio.Factor f) {
            return base.Channel.GuardarAsync(f);
        }
        
        public void Eliminar(WebMVC.FactorABMCServicio.Factor f) {
            base.Channel.Eliminar(f);
        }
        
        public System.Threading.Tasks.Task EliminarAsync(WebMVC.FactorABMCServicio.Factor f) {
            return base.Channel.EliminarAsync(f);
        }
        
        public WebMVC.FactorABMCServicio.Factor GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<WebMVC.FactorABMCServicio.Factor> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
    }
}
